### ISSUE TITLE
Problem: HTML5 popup stays displayed until you click on it

### ISSUE THREAD

**Issue by kijanawoodard** [ijoey/devchitchat#15]
This is annoying, especially when you are *in* dev chit chat. It covers useful parts of other apps.
For the record, it IS nice to get the notification when you're not looking at DCC, so keep it.

P.S. Trying to write up an issue as a problem statement per Hintjens. 
https://www.youtube.com/watch?v=xFVDNTXIC_Y

**Comment by kijanawoodard** [comment]
Suggested solutions:

It should toast and disappear after a while.
If you are active in dev chit chat, you don't need the html5 notification. By active I mean, have posted and DCC is still active app [might not be possible to know].

**Comment by ijoey** [comment]
I did 2 things, set a timer to dismiss the notification after about 3 seconds and track the users activity timestamp. >= 20 seconds of inactivity/not sending a message results in getting a message notification.
