### ISSUE TITLE
Convert URLs into anchor tags

### ISSUE THREAD

**Issue by ijoey** [ijoey/devchitchat#3]
Given that I am an authenticated user
When I chat a fully qualified URL
Then I can click on the link
And it opens in a new tab or window.

**Comment by kijanawoodard** [comment]
oh good, you already covered "And it opens in a new tab or window."

Now how are you gonna stop SEO Spammers?

**Comment by ijoey** [comment]
I don't know. Any suggestions? Bayesian filter before posting the message?

**Comment by ijoey** [comment]
Did this but you don't have to have a fully qualified url. It can be something like google.com and it'll convert that too. Haven't had spammers yet, so I don't know what the use cases are for that yet to solve it.
